# Generated by Django 2.2.19 on 2021-03-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('buku', '0002_buku_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_buat', models.DateField(auto_now_add=True, null=True)),
                ('tanggal_pinjam', models.DateField(null=True)),
                ('tanggal_kembali', models.DateField(null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.Buku')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaksi.StatusTransaksi')),
            ],
        ),
    ]
