# Generated by Django 2.2.19 on 2021-03-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=80)),
                ('penulis', models.CharField(max_length=80)),
                ('penerbit', models.CharField(max_length=80)),
                ('tahun', models.IntegerField(null=True)),
                ('sinopsis', models.CharField(max_length=300)),
                ('tanggal', models.DateField(auto_now_add=True, null=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buku.Genre')),
            ],
        ),
    ]
