# Generated by Django 2.2.19 on 2021-03-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KodeKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.IntegerField()),
                ('nama', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('no_telp', models.CharField(max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.KodeKelas')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Level')),
            ],
        ),
    ]
